### ISSUE TITLE
Suggestion to add tutorial on using social login such as google

### ISSUE THREAD

**Issue by helpme1** [pythonlessons/Django_tutorials#10]
Thanks for your excellent Django tutorials! I have a suggestion.

Nowadays, most websites allow log-in using social media accounts such as Google or Twitter. It will be wonderful if you can add this tutorial. Thanks.

**Comment by pythonlessons** [comment]
Thanks, I'll consider this!

**Comment by helpme1** [comment]
Great job. I see you have done it!!
https://pylessons.com/django-google-oauth
